### ISSUE TITLE
Responsiveness of 2 graphs on the same page

### ISSUE THREAD

**Issue by ped59430** [David-Desmaisons/vue-plotly#11]
Hi,
I am under the impression that there are special cases when 2 graphs cannot update their width at the same time.
I have a Vue page with 2 graphs. The size of the graph 2 is not updating.
If I remove the graph 1, then the graph 2 updates properly.
I really cannot figure out why !

**Comment by ped59430** [comment]
What I mean by special is:
- I use [element-ui](https://element.eleme.cn/#/en-US/component)
- It happens when I **set a fixed height** to both graphs, either by `style="height:600px"` or in the `layout` object with `height : 600`.
- It only happens in a [Tab component](https://element.eleme.cn/#/en-US/component/tabs#tabs)

Would you have any knowledge on the responsive mechanism that would explain this behaviour?

**Comment by ped59430** [comment]
In `src/components/Plotly.vue`, I have seen:
`return Object.assign(optionsFromAttrs, { responsive: false });`

Is there a reason that on any passed option `responsive` is set to `false`?

**Comment by ped59430** [comment]
For some unknow reasons, the `autosize: true` attribute is not passed to the `innerLayout` of the second graph.

When I force it in my `layout`:
```
layout: {
  autosize: true
}
```
I have:
![image](https://user-images.githubusercontent.com/9555650/72268549-4d2ffd00-3622-11ea-9ab4-71a960b46177.png)

And the graph extends to the current window size graph ! But it is not yet responsive to changes.

And I still have:
![image](https://user-images.githubusercontent.com/9555650/72270523-946bbd00-3625-11ea-80fa-8610a53df58e.png)

**Comment by ped59430** [comment]
I removed any custom heights for the moment. I hope it is possible to see

For the record, without any `options`, and my graphs **being really responsive**, I still have:
![image](https://user-images.githubusercontent.com/9555650/72270696-ddbc0c80-3625-11ea-98e1-c36abc838a96.png)

**Comment by Codermar** [comment]
> In `src/components/Plotly.vue`, I have seen:
> `return Object.assign(optionsFromAttrs, { responsive: false });`
> 
> Is there a reason that on any passed option `responsive` is set to `false`?

I am not sure why but I also need to be able to pass the responsive option in. I'll create a PR for that

**Comment by Codermar** [comment]
Added https://github.com/David-Desmaisons/vue-plotly/pull/12

**Comment by David-Desmaisons** [comment]
@Codermar responsive is set to false because responsiveness is provided by vue-resize that offers reactivity based on resize on the main element (plotty responsiveness only reacts to window size changes - at least at the tim at testesd it).
So you would not need to set { responsive: true }  as a plotly options. Try the online example https://david-desmaisons.github.io/vue-plotly/ it resize without problem.

So to make yopur component responsive you just need to include it in a responsive container and it will work.

**Comment by Codermar** [comment]
@David-Desmaisons I did try and it does not work for me actually. It does a resize on expanding the page but not on resize down and my container is responsive so something must be going on there.

**Comment by David-Desmaisons** [comment]
@Codermar I don't remenber why but I had to set the responsive to false because it was not playing well with the resize provided by the directive.

> Maybe it is related to the fact that my code applies data and layout dynamically and the resize down does not get triggered.
Could you provide an animated gif of the scenario with and without changing responsive to true. I am curious of you user case.

> Perhaps it can be set only if the user did not specify it.
Definitivelly a better option than forcing it to true.

**Comment by David-Desmaisons** [comment]
With responsive option set to false:
![with current option set to false](https://user-images.githubusercontent.com/524617/72852621-e64bbd00-3c8d-11ea-9c53-43bdbf1ab3ec.gif)

With responsive  option set to true:
![with responsive true option](https://user-images.githubusercontent.com/524617/72852625-e8ae1700-3c8d-11ea-878b-53256193044f.gif)

**Comment by David-Desmaisons** [comment]
Fixed in version 1.1.0
